# Generated by Django 3.1.3 on 2020-12-14 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='count_rate_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='books',
            name='rate_all_stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='ratting',
            field=models.ManyToManyField(related_name='book_rating', through='manager.BookRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
