# Generated by Django 3.1.3 on 2020-12-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20201203_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pub_office',
            options={'verbose_name': 'Издательства', 'verbose_name_plural': 'Издательства'},
        ),
    ]
