# Generated by Django 3.1.3 on 2020-12-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20201214_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='buyers',
            new_name='author',
        ),
    ]
