# Generated by Django 3.1.3 on 2020-12-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20201203_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр ', 'verbose_name_plural': 'Жанры'},
        ),
    ]
