# Generated by Django 3.1.3 on 2020-12-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_commentlikes_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='comment_likes',
        ),
    ]
