# Generated by Django 3.1.3 on 2020-12-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_comment_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
