# Generated by Django 3.1.3 on 2020-12-22 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0009_auto_20201222_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpbooks',
            name='author',
            field=models.ManyToManyField(related_name='tmp_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tmpbooks',
            name='published',
            field=models.DateTimeField(verbose_name='Время публикации'),
        ),
    ]
