# Generated by Django 3.1.3 on 2020-12-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20201205_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='like',
            new_name='likes',
        ),
    ]
