# Generated by Django 3.1.3 on 2020-12-23 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_auto_20201222_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('tmp_book', 'user')},
        ),
        migrations.RemoveField(
            model_name='bookrating',
            name='book',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
