# Generated by Django 3.1.3 on 2020-12-23 12:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0012_auto_20201223_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TMPBooks',
            new_name='Books',
        ),
        migrations.RenameField(
            model_name='bookrating',
            old_name='tmp_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='tmp_book',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('book', 'user')},
        ),
    ]
